version: "3.2"
services:
  las:
    image: registry.scontain.com:5050/sconecuratedimages/las:microsoft-azure-scone5.7
    environment:
      - SCONE_LOG=DEBUG
    devices:
      - "$DEVICE"
    privileged: true
    ports:
      - "18766:18766"
    networks:
      lld_network:
        ipv4_address: 172.20.0.2
  lld-dqlite:
    image: "pixix4/scone-dqlite"
    devices:
      - "$DEVICE"
    entrypoint: /bin/sh
    command: -c "sleep 20; SCONE_CAS_ADDR=$SCONE_CAS_ADDR LLD_SESSION=$LLD_SESSION /dqlite-entrypoint-scone.sh"
    depends_on:
      - las
    privileged: true
    networks:
      lld_network:
        ipv4_address: 172.20.0.11
  lld-server-dqlite:
    image: "pixix4/server-scone-dqlite"
    devices:
      - "$DEVICE"
    entrypoint: /bin/sh
    command: -c "sleep 30; SCONE_LOG=DEBUG SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$LLD_SESSION/server_dqlite /usr/local/bin/lld-server"
    depends_on:
      - las
      - lld-dqlite
    privileged: true
    ports:
      - "3030:3030"
      - "3040:3040"
    networks:
      lld_network:
        ipv4_address: 172.20.0.3

networks:
  lld_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
