version: "3.2"
services:
  lld-server-sqlite:
    image: "pixix4/server-native-sqlite"
    command: --mode=Batching
    ports:
      - "3030:3030"
      - "3040:3040"
    environment:
      - mode=Batching
      - sqlite_optimization=true
    networks:
      lld_network:
        ipv4_address: 172.20.0.3

networks:
  lld_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
